name: MTBlockModels
version: '1.0-SNAPSHOT'
main: me.darksoul.mTBlockModels.MTBlockModels
api-version: '1.20'
dependencies:
  server:
    Minetorio:
      load: BEFORE
      required: true
      join-classpath: true
